import streamlit as st
st.set_page_config(page_title="QuLab", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab: Operational Risk Assessment Lifecycle Simulator")
st.divider()
st.markdown("""
In this lab, we will explore the Operational Risk Assessment Lifecycle Simulator. This application provides an interactive simulation of the operational risk assessment lifecycle within a financial institution, as described in the "PRMIA Operational Risk Manager Handbook".

**Key Learning Outcomes:**
*   Understand the key stages and flow of a robust operational risk assessment program.
*   Learn how top-down risk identification informs bottom-up control assessment.
*   Explore the interplay between inherent risk, control effectiveness, and residual risk.
*   Recognize the importance of clear taxonomies and consistent tracking in risk management.
""")
# Your code starts here
page = st.sidebar.selectbox(label="Navigation", options=["Overview & Loss Data Simulation", "Risk Assessment"])
if page == "Overview & Loss Data Simulation":
    from application_pages.loss_data_simulation import run_overview_loss_simulation
    run_overview_loss_simulation()
elif page == "Risk Assessment":
    from application_pages.risk_assessment import run_risk_assessment
    run_risk_assessment()
# Your code ends


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
